SELECT 
    TH.ID_TIPO,
    TH.NOMBRE_TIPO,
    TH.COSTO_BAJA,
    TH.COSTO_ALTA,
    TH.DIMENSIONES,
    TH.TIPO_VISTA,
    TH.CANTIDAD_CAMAS,
    COUNT(H.NUMERO_HABITACION) AS HABITACIONES_DISPONIBLES
FROM TIPO_HABITACIONES TH
JOIN HABITACIONES H 
    ON TH.ID_TIPO = H.ID_TIPO  AND H.ID_HOTEL = 'H007' AND H.ESTADO_HABITACION = 'ACTIVA'
WHERE TH.ID_HOTEL = 'H007'
  AND NOT EXISTS (
    SELECT * FROM RESERVAS R
    WHERE R.ID_TIPO = TH.ID_TIPO AND R.ESTADO NOT IN ('CANCELADA') AND R.FECHA_ENTRADA < DATE '2026-12-01' AND R.FECHA_SALIDA > DATE '2026-11-01'
  )
GROUP BY 
    TH.ID_TIPO, TH.NOMBRE_TIPO, TH.COSTO_BAJA, 
    TH.COSTO_ALTA, TH.DIMENSIONES, TH.TIPO_VISTA, TH.CANTIDAD_CAMAS
ORDER BY TH.NOMBRE_TIPO;