SELECT C.NOMBRE_CIUDAD, H.NOMBRE_HOTEL, TO_CHAR(R.FECHA_ENTRADA,'YYYY-MM') AS MES,COUNT(R.ID_RESERVA) AS TOTAL_RESERVAS 
FROM RESERVAS R 
JOIN TIPO_HABITACIONES TH ON R.ID_TIPO = TH.ID_TIPO
JOIN HOTELES H ON TH.ID_HOTEL = H.ID_HOTEL 
JOIN CIUDADES C ON H.ID_CIUDAD = C.ID_CIUDAD 
WHERE R.ESTADO NOT IN ('CANCELADA') 
AND R.FECHA_ENTRADA >= TO_DATE(:P3_FECHA_INICIO,'YYYY-MM-DD') 
AND R.FECHA_ENTRADA <= TO_DATE(:P3_FECHA_FIN,'YYYY-MM-DD') 
AND (:P3_ID_HOTEL IS NULL OR H.ID_HOTEL = :P3_ID_HOTEL) 
AND (:P3_ID_CIUDAD IS NULL OR C.ID_CIUDAD = :P3_ID_CIUDAD) 
GROUP BY C.NOMBRE_CIUDAD, H.NOMBRE_HOTEL, TO_CHAR(R.FECHA_ENTRADA,'YYYY-MM') 
ORDER BY MES, H.NOMBRE_HOTEL;