SELECT C.NOMBRE_CIUDAD, H.NOMBRE_HOTEL, SUM(R.ADULTOS +R.NINOS) AS TOTAL_HUESPEDES, COUNT(R.ID_RESERVA) AS TOTAL_RESERVAS
FROM RESERVAS R
JOIN TIPO_HABITACIONES TH ON R.ID_TIPO = TH.ID_TIPO
JOIN HOTELES H ON TH.ID_HOTEL = H.ID_HOTEL
JOIN CIUDADES C ON H.ID_CIUDAD = C.ID_CIUDAD
WHERE R.ESTADO NOT IN ('CANCELADA')
  AND R.FECHA_ENTRADA <= TO_DATE(:P4_FECHA_FIN, 'YYYY-MM-DD')
  AND R.FECHA_SALIDA >= TO_DATE(:P4_FECHA_INICIO, 'YYYY-MM-DD')
  AND C.ID_CIUDAD = :P4_ID_CIUDAD
  AND ( H.ID_HOTEL = :P4_ID_HOTEL)
GROUP BY C.NOMBRE_CIUDAD, H.NOMBRE_HOTEL
ORDER BY TOTAL_HUESPEDES DESC
