SELECT 
    C.NOMBRE_CIUDAD AS LABEL, SUM(R.PRECIO_TOTAL) AS VALUE
FROM RESERVAS R
JOIN TIPO_HABITACIONES TH ON R.ID_TIPO = TH.ID_TIPO
JOIN HOTELES H ON TH.ID_HOTEL = H.ID_HOTEL
JOIN CIUDADES C ON H.ID_CIUDAD = C.ID_CIUDAD
WHERE R.ESTADO NOT IN ('CANCELADA')
  AND TO_CHAR(R.FECHA_ENTRADA, 'YYYY') = :P5_ANO
GROUP BY C.NOMBRE_CIUDAD
ORDER BY SUM(R.PRECIO_TOTAL) DESC

SELECT 
    H.NOMBRE_HOTEL AS LABEL,
    SUM(R.PRECIO_TOTAL) AS VALUE
FROM RESERVAS R
JOIN TIPO_HABITACIONES TH ON R.ID_TIPO = TH.ID_TIPO
JOIN HOTELES H ON TH.ID_HOTEL = H.ID_HOTEL
JOIN CIUDADES C ON H.ID_CIUDAD = C.ID_CIUDAD
WHERE R.ESTADO NOT IN ('CANCELADA')
  AND TO_CHAR(R.FECHA_ENTRADA, 'YYYY') = :P5_ANO
GROUP BY H.NOMBRE_HOTEL
ORDER BY SUM(R.PRECIO_TOTAL) DESC