SELECT S.NOMBRE AS LABEL, SUM(RS.CANTIDAD) AS VALUE
FROM RESERVAS R
JOIN RESERVA_SERVICIOS RS ON R.ID_RESERVA = RS.ID_RESERVA
JOIN SERVICIOS S ON RS.ID_SERVICIO = S.ID_SERVICIO
JOIN TIPO_HABITACIONES TH ON R.ID_TIPO = TH.ID_TIPO
JOIN HOTELES H ON TH.ID_HOTEL = H.ID_HOTEL
WHERE R.ESTADO NOT IN ('CANCELADA')
  AND H.ID_HOTEL = :P6_ID_HOTEL
  AND R.FECHA_ENTRADA >= TO_DATE(:P6_FECHA_INICIO, 'YYYY-MM-DD')
  AND R.FECHA_ENTRADA <= TO_DATE(:P6_FECHA_FIN, 'YYYY-MM-DD')
GROUP BY S.NOMBRE
ORDER BY SUM(RS.CANTIDAD) DESC


SELECT  TH.NOMBRE_TIPO AS LABEL,COUNT(R.ID_RESERVA) AS VALUE
FROM RESERVAS R
JOIN TIPO_HABITACIONES TH ON R.ID_TIPO = TH.ID_TIPO
JOIN HOTELES H ON TH.ID_HOTEL = H.ID_HOTEL
WHERE R.ESTADO NOT IN ('CANCELADA')
  AND H.ID_HOTEL = :P6_ID_HOTEL
  AND R.FECHA_ENTRADA >= TO_DATE(:P6_FECHA_INICIO, 'YYYY-MM-DD')
  AND R.FECHA_ENTRADA <= TO_DATE(:P6_FECHA_FIN, 'YYYY-MM-DD')
GROUP BY TH.NOMBRE_TIPO
ORDER BY COUNT(R.ID_RESERVA) DESC